stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/twitter_sentiment.csv
    - src/prepare.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train:
    cmd: \
