stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw/twitter_sentiment.csv
      - src/prepare.py
    outs:
      - data/processed/test.csv
      - data/processed/train.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/test.csv
      - data/processed/train.csv
      - src/train.py
    outs:
      - models/logreg.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/logreg.pkl
    outs:
      - metrics.txt

